version: "3.7"
services:
  cf-companion:
    image: tiredofit/traefik-cloudflare-companion:${IMAGETAG_CFCOMPANION}
    container_name: cf-companion
    env_file:
      - ${HOMESERVER_DIR}/cf-companion/cf-companion.env
    networks:
      - t2_proxy
      - socket_proxy
    restart: always
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.http.routers.cf-companion-rtr.rule=HostHeader(`cockpit.${FQDN}`) || HostHeader(`tvheadend.${FQDN}`)"
