version: "3.7"
services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:${IMAGETAG_SONARR}
    container_name: sonarr
    networks:
      - t2_proxy
    env_file:
      - ${HOMESERVER_DIR}/sonarr/sonarr.env
    volumes:
      - ${BASE_DIR}/sonarr/data/config:/config
      - ${BASE_DIR}/qbittorrent/data/downloads:/downloads
      - ${MEDIA_DIR}:/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers no Auth
      - "traefik.http.routers.sonarr-rtr-bypass.entrypoints=http,https"
      - "traefik.http.routers.sonarr-rtr-bypass.rule=Host(`sonarr.${FQDN}`) && (Headers(`X-Api-Key`, `${SONARR_APIKEY}`) || Query(`apikey`, `${SONARR_APIKEY}`))"
      - "traefik.http.routers.sonarr-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.sonarr-rtr.entrypoints=http,https"
      - "traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.${FQDN}`)"
      - "traefik.http.routers.sonarr-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.sonarr-rtr-bypass.middlewares=chain-no-oauth@file"
      - "traefik.http.routers.sonarr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.sonarr-rtr.service=sonarr-svc"
      - "traefik.http.routers.sonarr-rtr-bypass.service=sonarr-svc"
      - "traefik.http.services.sonarr-svc.loadbalancer.server.port=8989"

