- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: started # may be absent or started
    name: "{{ container_name }}4k"
    image: "{{ linuxserver_registry }}/{{ container_name }}:{{ image_tag }}"
    pull: true
    networks:
      - name: "{{ main_network }}"
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
    mounts:
      - type: "bind"
        propagation: "rslave"
        source: "{{ media_dir }}"
        target: "/data"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}4k/data/config:/config"
      - "{{ docker_dir }}/qbittorrent/data/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "true"
      "traefik.http.routers.radarr4k-rtr.entrypoints": "web, websecure"
      "traefik.http.routers.radarr4k-rtr.rule": "Host(`4k{{ container_name }}.{{ fqdn }}`)"
      ## Middlewares
      "traefik.http.routers.radarr4k-rtr.middlewares": "{{ 'chain-oauth@file' if oauth == true else 'chain-no-oauth@file' }}"
      ## HTTP Services
      "traefik.http.routers.radarr4k-rtr.service": "radarr4k-svc"
      "traefik.http.services.radarr4k-svc.loadbalancer.server.port": "7878"
