version: "3.7"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati:${IMAGETAG_PLEX}
    container_name: duplicati
    networks:
      - t2_proxy
    env_file:
      - ${HOMESERVER_DIR}/duplicati/duplicati.env
    volumes:
      - ${BASE_DIR}/duplicati/data/config:/config
      - ${BASE_DIR}:/source
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    labels:
      ## HTTP Routers
      - "traefik.enable=true"
      - "traefik.http.routers.duplicati-rtr.entrypoints=http,https"
      - "traefik.http.routers.duplicati-rtr.rule=Host(`duplicati.${FQDN}`)"
      ## Middlewares
      - "traefik.http.routers.duplicati-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.duplicati-rtr.service=duplicati-svc"
      - "traefik.http.services.duplicati-svc.loadbalancer.server.port=8200"
    
