# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: "http://{{ adguard_main_host }}:3000"
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: "{{ adguard_user }}"
  password: "{{ adguard_password }}"

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: "http://{{ adguard_replica_host }}:3000"
  username: "{{ adguard_user }}"
  password: "{{ adguard_password }}"

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API 
  #  username: "{{ adguard_user }}"
  #  password: "{{ adguard_password }}"

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
