- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: absent # may be absent or started
    name: "{{ container_name }}"
    image: "aunefyren/{{ container_name }}:{{ image_tag }}"
    pull: true
    networks:
      - name: "{{ main_network }}"
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data/config:/app/config"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "true"
      "traefik.http.routers.wrapperr-rtr.entrypoints": "web, websecure"
      "traefik.http.routers.wrapperr-rtr.rule": "Host(`{{ container_name }}.{{ fqdn }}`)"
      ## Middlewares
      "traefik.http.routers.wrapperr-rtr.middlewares": "{{ 'chain-oauth@file' if oauth == true else 'chain-no-oauth@file' }}"
      ## HTTP Services
      "traefik.http.routers.wrapperr-rtr.service": "wrapperr-svc"
      "traefik.http.services.wrapperr-svc.loadbalancer.server.port": "8282"
