- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: started # may be absent or started
    name: "{{ container_name }}"
    image: "tecnativa/docker-socket-proxy:{{ image_tag }}"
    pull: true
    networks:
      - name: "{{ socket_network }}"
        ipv4_address: 10.0.124.254
    purge_networks: true
    privileged: true
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
      "LOG_LEVEL": "err"
      "EVENTS": "1"
      "VERSION": "1"
      "AUTH": "0"
      "SECRETS": "0"
      "POST": "1"
      "BUILD": "0"
      "COMMIT": "0"
      "CONFIGS": "0"
      "CONTAINERS": "1"
      "DISTRIBUTION": "0"
      "EXEC": "0"
      "IMAGES": "1" # Change to 1 for Portainer or docker-gc
      "INFO": "1" # Change to 1 for Portainer or docker-gc
      "NETWORKS": "1" # Change to 1 for Portainer or docker-gc
      "NODES": "0"
      "PLUGINS": "0"
      "SERVICES": "1" # Change to 1 for Portainer or docker-gc
      "SESSION": "0"
      "SWARM": "0"
      "SYSTEM": "0"
      "TASKS": "1" # Change to 1 for Portainer or docker-gc
      "VOLUMES": "1" # Change to 1 for Portainer or docker-gc
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "false"
