- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: started # may be absent or started
    name: "{{ container_name }}"
    image: "{{ container_name }}:{{ image_tag }}"
    pull: true
    networks:
      - name: "{{ main_network }}"
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
      "TS3SERVER_LICENSE": "accept"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data/:/var/ts3server/"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "true"
      "traefik.udp.routers.ts3-rtr.entrypoints": "teamspeak"
      "traefik.udp.routers.ts3-rtr.service": "ts3-svc"
      "traefik.udp.services.ts3-svc.loadbalancer.server.port": "{{ ts3_port }}"
