- name: Make sure the container is created and running - postgres-{{ container_name }}
  community.docker.docker_container:
    state: absent # may be absent or started
    name: "{{ container_name }}-postgres"
    image: "postgres:13"
    pull: true
    networks:
      - name: "{{ main_network }}"
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
      "POSTGRES_PASSWORD": "{{ POSTGRES_PASSWORD_JOPLIN }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data/config:/config"
      - "{{ docker_dir }}/qbittorrent/data/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"

- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: absent # may be absent or started
    name: "{{ container_name }}"
    image: "{{ linuxserver_registry }}/{{ container_name }}:{{ image_tag }}"
    pull: true
    networks:
      - name: t2_proxy
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
      "DELUGE_LOGLEVEL": "error"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data/config:/config"
      - "{{ docker_dir }}/qbittorrent/data/downloads:/downloads"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "true"
      "traefik.http.routers.joplin-rtr.entrypoints": "web, websecure"
      "traefik.http.routers.joplin-rtr.rule": "Host(`{{ container_name }}.{{ fqdn }}`)"
      ## Middlewares
      "traefik.http.routers.joplin-rtr.middlewares": "{{ 'chain-oauth@file' if oauth == true else 'chain-no-oauth@file' }}"
      ## HTTP Services
      "traefik.http.routers.joplin-rtr.service": "joplin-svc"
      "traefik.http.services.joplin-svc.loadbalancer.server.port": "8112"
