- name: Make sure the container is created and running - {{ container_name }}
  community.docker.docker_container:
    state: started # may be absent or started
    name: "{{ container_name }}"
    image: "{{ linuxserver_registry }}/plex:{{ image_tag }}"
    pull: true
    networks:
      - name: "{{ main_network }}"
        ipv4_address: 10.0.123.150
    purge_networks: true
    privileged: false
    security_opts: no-new-privileges:true
    restart_policy: unless-stopped
    devices:
      - "/dev/dri:/dev/dri"
    env:
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "UMASK": "{{ umask }}"
      "TZ": "{{ timezone }}"
      "VERSION": "latest"
    mounts:
      - type: "bind"
        propagation: "rslave"
        source: "{{ media_dir }}"
        target: "/data"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data/library:/config"
      - "/dev/shm:/transcoding"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      ## HTTP Routers
      "traefik.enable": "true"
      "traefik.http.routers.plex-rtr.entrypoints": "web, websecure"
      "traefik.http.routers.plex-rtr.rule": "Host(`plex.{{ fqdn }}`)"
      ## Middlewares
      "traefik.http.routers.plex-rtr.middlewares": "{{ 'chain-oauth@file' if oauth == true else 'chain-no-oauth@file' }}"
      ## HTTP Services
      "traefik.http.routers.plex-rtr.service": "plex-svc"
      "traefik.http.services.plex-svc.loadbalancer.server.port": "32400"
