- name: Enable community repositories
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/apk/repositories"
    state: present
    line: 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/community'

- name: Ensure docker is installed
  become: true
  ansible.builtin.package:
    name:
      - docker
      - openrc
      - py-setuptools
      - python3-dev
      - py3-pip
    state: present

- name: Install Docker Module for Python
  ansible.builtin.pip:
    name: docker

- name: Start service docker, if not started
  become: true
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started

- name: Add default user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - docker
    state: present
    append: true
